# Generated by Django 3.2.15 on 2022-10-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
