# Generated by Django 3.2.15 on 2022-10-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placeimage_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placeimage',
            unique_together={('place', 'position')},
        ),
    ]
