# Generated by Django 4.1.2 on 2022-10-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_placeimage_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ('position',), 'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AlterUniqueTogether(
            name='placeimage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
