# Generated by Django 4.1.2 on 2022-10-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_placeimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, default=1, null=True),
        ),
    ]
